name: Python Package using Conda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: test
      run: |
        python3 -m unittest BinanceSymbolFetching/test/*test.py
